### ISSUE TITLE
(feat) FluentBit kubernetes_events input plugin

### ISSUE THREAD

**Issue by jjsiv** [fluent/fluent-operator#1001]
### Is your feature request related to a problem? Please describe.

FluentBit introduced kubernetes_events plugin in 2.15 or so. Would be nice to be able to define it in the Fluent Operator native way.

### Describe the solution you'd like

kubernetesEvents plugin in ClusterInput/Input for FluentBit

**Comment by jjsiv** [comment]
I will pick this up some time next week.

**Comment by Cajga** [comment]
We would also love to use this. @jjsiv, have you had time to look at it?

**Comment by smallc2009** [comment]
I have created a PR to add this feature.
