### ISSUE TITLE
feature request: Add copy output plugin for Fluentd

### ISSUE THREAD

**Issue by antrema** [fluent/fluent-operator#1017]
### Is your feature request related to a problem? Please describe.

The copy plugin for Fluentd is not available, so we cannot configure multiple outputs (See #874)

### Describe the solution you'd like

Implementation of the `copy`output plugin for Fluentd

**Comment by antrema** [comment]
@benjaminhuo @wenchajun I would like to have your opinion about my proposal before working on the code

**Comment by benjaminhuo** [comment]
> @benjaminhuo @wenchajun I would like to have your opinion about my proposal before working on the code

@antrema That's a big enhancement. Thanks for your proposal!
I'm ok with this proposal, @wanjunlei @wenchajun what do you think?
