### ISSUE TITLE
Datadog fluentbit ouput plugin Api Key secret

### ISSUE THREAD

**Issue by javi-rodriguez-chainalysis** [fluent/fluent-operator#1060]
### Is your feature request related to a problem? Please describe.

When configuring the Datadog fluentbit output plugin, API key has to be passed as a raw string and does not allow for secret injection. 

https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/plugins/output/datadog_types.go#L24

### Describe the solution you'd like

Be able to pass the API key as a secret like in fluentd
https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/plugins/output/datadog.go#L8

**Comment by nitintecg** [comment]
Hi @wenchajun ,
I'm currently learning k8s. i'm interested in contributing to this issue. 
I have one question for this do we to update tests files for this change ? 
Thanks

**Comment by wenchajun** [comment]
Yes, we need to refine the test file, please refer to ： https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/plugins/output/datadog_types_test.go
