### ISSUE TITLE
Support output level processors for Fluent Bit

### ISSUE THREAD

**Issue by jeff303** [fluent/fluent-operator#1151]
### Is your feature request related to a problem? Please describe.

Fluent Bit supports specifying processors at the output level (see [here](https://github.com/fluent/fluent-bit-docs/blob/master/administration/configuring-fluent-bit/yaml/configuration-file.md)).  It would be great if support for this was added to Fluent Operator, so that we could propagate such processors at the CRD level.

### Describe the solution you'd like

Add support for processor configuration under outputs, where applicable.  It looks like this is only supported under YAML configuration, so #1008 would need to be done first.

**Comment by cw-Guo** [comment]
@jeff303 Just want to let you know, we have supported this feature via https://github.com/fluent/fluent-operator/pull/1208
