### ISSUE TITLE
bug: Unable to extract namespace from Kuberenetes filter

### ISSUE THREAD

**Issue by Karthika-Pingali** [fluent/fluent-operator#1193]
### Describe the issue

To enhance the logs we have tried the kubernetes filter and set the **useKubelet** as **true** . But we are getting the kubelet upstream error. Even tried with latest version but it the same issue. 
![image](https://github.com/fluent/fluent-operator/assets/113021390/faeb395c-b2dc-4e1b-b17d-cfd2383d1b6b)

Is there a way where we can get extract the namespace and pod name apart from the custom regex expressions??
 

### To Reproduce

We have tried the kubernetes filter and set the **useKubelet** as **true** . But we are getting the kubelet upstream error. 

### Expected behavior

It needs to extract the namespace and pd name etc.,

### Your Environment

```markdown
- Fluent Operator version: v2.7.0
```

**Comment by cw-Guo** [comment]
@Karthika-Pingali See https://docs.fluentbit.io/manual/pipeline/inputs/tail Tag_Regex

**Comment by SvenThies** [comment]
@Karthika-Pingali does this resolve this issue? Can it be closed?
