### ISSUE TITLE
Support out-of-band image updates for fluentd and fluentbit

### ISSUE THREAD

**Issue by joshuabaird** [fluent/fluent-operator#1241]
### Is your feature request related to a problem? Please describe.

We currently build and release `fluentbit` and `fluentd` images which track their upstream versions.  For example, our `ghcr.io/fluent/fluent-operator/fluent-bit:v3.10` image is based off of the `fluent/fluent-bit:3.1.2` image.

Our images often contain customizations, etc -- for example, our [fluentd](https://github.com/fluent/fluent-operator/tree/master/cmd/fluent-watcher/fluentd) image installs several fluentd [plugins](https://github.com/fluent/fluent-operator/blob/e0d936ddfe45c8588159fd436e47f897457f6d26/cmd/fluent-watcher/fluentd/Dockerfile.amd64#L38).

Presently, if we want to make changes to these custom artifacts (eg, update a plugin), we have to build a new image which overrides an existing tag.  This is troublesome for a few reasons -- mainly, our users don't expect potentially breaking changes between images when they are pinned to a specific tag (eg, `ghcr.io/fluent/fluent-operator/fluent-bit:v3.10`).

### Describe the solution you'd like

We need a way to build and release new images without overwriting our existing tags.  One option would be to introduce a "patch version" in our versioning -- eg `fluent-bit:v3.10.1`).  In this case, the image would still be based off of `fluent/fluent-bit:3.10`, but would include any custom changes (eg, plugin upgrades) that we wanted to include in the image.

@benjaminhuo @wenchajun Do you have any suggestions or opinions on this?

**Comment by benjaminhuo** [comment]
I agree.
A few comments:
- ghcr.io/fluent/fluent-operator/fluent-bit:v3.1.2 (not v3.10) is based off fluent/fluent-bit:3.1.2 
![image](https://github.com/user-attachments/assets/a619c94a-e9d5-4313-ac27-6a2ce605c202)
- let's say fluentbit has v3.1.10, and fluent operator's custom image should be called v3.1.10.20240506 or v3.1.10.xx
or v3.1.10+20240506 

The change requires corresponding changes to the github workflow for build image which should be changed accordingly

cc @wanjunlei

**Comment by joshuabaird** [comment]
Ah yes - sorry, the tag was a typo.  `ghcr.io/fluent/fluent-operator/fluent-bit:v3.1.2` is based off of `fluent/fluent-bit:3.1.2`.

I agree about the versioning pattern.  I'll try to get started on a PR soon to address this.

**Comment by joshuabaird** [comment]
As for the tagging logic, here is what I'm thinking:

* Maintainer specifies `3.1.3` as the `docker_tag_version` in the [workflow](https://github.com/fluent/fluent-operator/blob/e0d936ddfe45c8588159fd436e47f897457f6d26/.github/workflows/build-fb-image.yaml#L6)
* If `ghcr.io/fluent/fluent-operator/fluent-bit:3.1.3` already exists
 * Do not tag `3.1.3` (we don't want to overwrite the existing image)
 * Tag `3.1.3-XX` (auto-incrementing patch version)
 * Tag `3.1`
* If `ghcr.io/fluent/fluent-operator/fluent-bit:3.1.3` does not already exist
 * Tag `3.1.3`
 * Tag `3.1.3-01`
 * Tag `3.1`

Any thoughts on this logic?

**Comment by benjaminhuo** [comment]
> As for the tagging logic, here is what I'm thinking:
> 
> * Maintainer specifies `3.1.3` as the `docker_tag_version` in the [workflow](https://github.com/fluent/fluent-operator/blob/e0d936ddfe45c8588159fd436e47f897457f6d26/.github/workflows/build-fb-image.yaml#L6)
> * If `ghcr.io/fluent/fluent-operator/fluent-bit:3.1.3` already exists
>   
>   * Do not tag `3.1.3` (we don't want to overwrite the existing image)
>   * Tag `3.1.3-XX` (auto-incrementing patch version)
>   * Tag `3.1`
>   * Tag `latest`
> * If `ghcr.io/fluent/fluent-operator/fluent-bit:3.1.3` does not already exist
>   
>   * Tag `3.1.3`
>   * Tag `3.1.3-01`
>   * Tag `3.1`
>   * Tag `latest`
> 
> Any thoughts on this logic? Need to look into how we may implement auto-incrementing the patch tag when necessary.

cc @wenchajun @wanjunlei

**Comment by joshuabaird** [comment]
PR to implement the logic described above:  https://github.com/fluent/fluent-operator/pull/1246

**Comment by sarathchandra24** [comment]
> > As for the tagging logic, here is what I'm thinking:
> > 
> > * Maintainer specifies `3.1.3` as the `docker_tag_version` in the [workflow](https://github.com/fluent/fluent-operator/blob/e0d936ddfe45c8588159fd436e47f897457f6d26/.github/workflows/build-fb-image.yaml#L6)
> > * If `ghcr.io/fluent/fluent-operator/fluent-bit:3.1.3` already exists
> >   
> >   * Do not tag `3.1.3` (we don't want to overwrite the existing image)
> >   * Tag `3.1.3-XX` (auto-incrementing patch version)
> >   * Tag `3.1`
> >   * Tag `latest`
> > * If `ghcr.io/fluent/fluent-operator/fluent-bit:3.1.3` does not already exist
> >   
> >   * Tag `3.1.3`
> >   * Tag `3.1.3-01`
> >   * Tag `3.1`
> >   * Tag `latest`
> > 
> > Any thoughts on this logic? Need to look into how we may implement auto-incrementing the patch tag when necessary.
> 
> cc @wenchajun @wanjunlei @sarathchandra24 @markusthoemmes what do you think?

LGTM; I thought 3.1.x -> x represents the patch version; but didn't realize it for synching the upstream. Agree with the approach as we want to maintain sync.
