### ISSUE TITLE
help request: how to expose a custom UDP port

### ISSUE THREAD

**Issue by tanzerm** [fluent/fluent-operator#1243]
### Describe the issue

I want to send logs from several appliances into Kubernetes. Therefore, I configured a ClusterInput:

```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  namespace: fluent
  name: fw-input
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "fluentbit-only"
spec:
  customPlugin:
    config: |
      Name    udp
      Listen      0.0.0.0
      Port        12222
      Chunk_Size  32
      Buffer_Size 64
      Format      none
      Tag         firewall.*
```

But the pods don't expose the specified port, and no related Kubernetes service is created.

### How did you install fluent operator?

installed via helm chart: `fluent-operator:3.0.0`

**Comment by cw-Guo** [comment]
service & port are either created via the helm chart template or in the operator. 

unfortunately, both of them have no idea about any customPlugin. 

You can try to resolve this issue by:

- support UDP plugin in the operator
- support UDP plugin in the helm chart
