### ISSUE TITLE
bug:  fluent-bit-config secret is created in fluent-operator namespace by default.

### ISSUE THREAD

**Issue by btalakola** [fluent/fluent-operator#1365]
### Describe the issue

Hi Team,
First of all would like to thank for the great work on the fluent-operator.
I have a requirement to deploy fluent-operator controller and fluent-bit daemonset in differnet namespaces. 
Able to deploy fluent-bit and fluent-operator in different namespaces by proving the namespace for fluent-operator deployment, serviceAccount, ClusterRoleBinding mapping explicitly. There is one more significant change where we need to give the "fluent-bit-config" namespace in the ClusterFluentBitConfig custom resource.
Currently "fluent-bit-config" secret is getting created in the fluent-operator namespace by default. It can be configured using "namespace" key from ClusterFluentBitConfig CRD but this namespace key is not configured at the CR level. 
https://github.com/fluent/fluent-operator/blob/release-3.2/charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusterfluentbitconfigs.yaml#L191-L231
I have a request here. Could you please make this namespace parameter configurable by adding to ClusterFluentBitConfig customresource > spec section.
https://github.com/fluent/fluent-operator/blob/release-3.2/charts/fluent-operator/templates/fluentbitconfig-fluentBitConfig.yaml#L10.

### To Reproduce

bug:  fluent-bit-config secret is created in fluent-operator namespace by default.

### Expected behavior

fluent-bit-config secret should be configured using namespace parameter.

### Your Environment

```markdown
- Fluent Operator version: v3.1.0
- Container Runtime: containerd
- Operating system: Ubuntu 22.04.4 LTS
```

### How did you install fluent operator?

Deploy fluent-bit using fluent-operator helm chart.

**Comment by cw-Guo** [comment]
this is a request for the helm chart template.

since we have the namespace defined [here](https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go), it's straightforward to add it to the helm [template](https://github.com/fluent/fluent-operator/blob/release-3.2/charts/fluent-operator/templates/fluentbitconfig-fluentBitConfig.yaml#L10) . 

@btalakola Would you mind please raising a PR to resolve it?
