### ISSUE TITLE
Publish new fluentd image with fluentd-plugin-opensearch v1.1.5

### ISSUE THREAD

**Issue by ntopee** [fluent/fluent-operator#1372]
### Is your feature request related to a problem? Please describe.

The current fluentd image (ghcr.io/fluent/fluent-operator/fluentd:v1.17.0) containts fluentd-plugin-opensearch v1.1.4. It has a bug that causes us some issues on EKS, that has been fixed in the latest release:
https://github.com/fluent/fluent-plugin-opensearch/releases/tag/v1.1.5

### Describe the solution you'd like

Publish a new fluentd image with the latest fluent-plugin-openserch gem.

**Comment by joshuabaird** [comment]
@ntopee `ghcr.io/fluent/fluent-operator/fluentd:v1.17.0-5` been published which contains `fluentd-plugin-opensearch:v1.1.5`.
