### ISSUE TITLE
help request: Fluentbit intermittent 404 issues on /api/v2/metrics/prometheus endpoint

### ISSUE THREAD

**Issue by mshivanna** [fluent/fluent-operator#1428]
### Describe the issue

We have installed 3.2.0 version of fluent operator helm chart and have enabled fluentbit to ship logs from k8s containers to opensearch in aws. When we turn on servicemonitor we see 404 on /api/v2/metrics/prometheus on different fluentbit pods at different times.
at t1: 
![image](https://github.com/user-attachments/assets/c2633244-6cf2-4deb-b4cf-c15e3376e10f)

at t2: 
![image](https://github.com/user-attachments/assets/a1462114-0fd5-4518-ac40-af994078e9ed)

### How did you install fluent operator?

helm chart version 3.2.0

**Comment by cw-Guo** [comment]
this looks more like a fluent-bit issue. Please raise the issue there. https://github.com/fluent/fluent-bit/issues

It's possible that your fluent-bit pods are not running healthy at that time.

**Comment by mshivanna** [comment]
ok Thanks. The metrics buffer is not getting populated and the server sends a 404.  https://github.com/fluent/fluent-bit/blob/master/src/http_server/api/v2/metrics.c#L181

**Comment by mshivanna** [comment]
similar issue while using prometheus exporter https://github.com/fluent/fluent-bit/issues/9366
