### ISSUE TITLE
Add CI templates  for fluentbit-operator

### ISSUE THREAD

**Issue by zhu733756** [fluent/fluent-operator#207]
Refer to https://github.com/fluent/fluentd/tree/master/.github

/help
/first-good-issue

**Comment by mangoGoForward** [comment]
I'd like to tackle this issue, and which elements must have in fluentbit-operator's CI templates?

/assign

**Comment by zhu733756** [comment]
> I'd like to tackle this issue, and which elements must have in fluentbit-operator's CI templates?
> 
> /assign

Glad to hear that, big mango brother!

**Comment by zhu733756** [comment]
> I'd like to tackle this issue, and which elements must have in fluentbit-operator's CI templates?
> 
> /assign

Except for workflows I think.  Needs to change the description for other files.
