### ISSUE TITLE
The wrong configuration file was generated

### ISSUE THREAD

**Issue by wenchajun** [fluent/fluent-operator#222]
Hi guys, I have installed fluent-operator using helm. it installed successfully and also deployed fluentd and fluentbit pods successfully. but I found out that these two pods are reporting errors by checking the logs. The configuration file it produced was different and produced a `@48b7c...` label under route. But after I delete the two profiles, these are [fluentd.yaml](https://github.com/fluent/fluentbit-operator/blob/master/charts/fluent-operator/templates/fluentd-fluentdconfig.yaml) and [cluster-fluentd-config.yaml](https://github.com/fluent/fluentbit-operator/blob/master/charts/fluent-operator/templates/fluentd-clusterfluentdconfig.yaml) .then everything works fine.
Can't a namespaced level configuration file and a cluster level configuration file exist at the same time? If not, we can specify this in the documentation.
![fc8f0a007c4255ea090779ad8310995](https://user-images.githubusercontent.com/39892300/155985555-59466428-183e-4f28-9d9a-17a4b83825cd.png)
![a0d46d8acf0264dcafdb5e432ad37d5](https://user-images.githubusercontent.com/39892300/155985566-edbffc0d-6fba-4e73-b365-93d5b2cf9e6c.png)

**Comment by benjaminhuo** [comment]
@zhu733756 what do you think?

**Comment by zhu733756** [comment]
Can't a namespaced level configuration file and a cluster level configuration file exist at the same time? 
> It could be exited at the same time, can you give your helm cmdline?

You see one cluster-level ClusterFluentdConfig or FluentdConfig will generate a route. Perhaps at least one filter or output should be defined?

**Comment by wenchajun** [comment]
> > Can't a namespaced level configuration file and a cluster level configuration file exist at the same time?
> 
> It could be exited at the same time, can you give your helm cmdline?
> 
> You see each one cluster-level ClusterFluentdConfig or namespace-level FluentdConfig will generate a route. Perhaps at least one filter or output should be defined?
> 
> I think this part can be optimized. I will see it later.

I used only one command to install.
```
helm install fluent-operator --create-namespace -n kubesphere-logging-system charts/fluent-operator/  --set Kubernetes=true,containerRuntime=crio,fluentd.enable=true
···

**Comment by benjaminhuo** [comment]
@zhu733756 Is this a bug we should fix?

**Comment by zhu733756** [comment]
> @zhu733756 Is this a bug we should fix?

I will test and fix it.
