### ISSUE TITLE
How can fluent-operator be consumed as a go module ?

### ISSUE THREAD

**Issue by davidovich** [fluent/fluent-operator#227]
I am trying to consume fluent-operator to allow scheme registration for using go-client to programmatically interface with the fluent-operator CRDs, but it is not possible to `go get fluent.io/fluent-operator`, it responds with a 404, and so does not implement the go module interface.

Using the github repo url does not work either as the declared module in the go mod is not the same as where it is served:

```bash
$ go get github.com/fluent/fluent-operator@master
go: downloading github.com/fluent/fluent-operator v0.4.1-0.20220307074933-9ebb28132f47
go get: github.com/fluent/fluent-operator@v0.4.1-0.20220307074933-9ebb28132f47: parsing go.mod:
        module declares its path as: fluent.io/fluent-operator
                but was required as: github.com/fluent/fluent-operator
```

There is one last possibility, using replace directives, but that should not be used just for the sake of import rewriting:

```go.mod
replace fluent.io/fluent-operator => github.com/fluent/fluent-operator v0.4.1-0.20220307074933-9ebb28132f47
```

Is there another way to achieve programmatic access to schemes aside from manually re-creating them in my project ?

Thanks

**Comment by zhu733756** [comment]
> @zhu733756 will fix this, you simply need to import github.com/fluent/fluent-operator

Yeah, i will fix it.

**Comment by davidovich** [comment]
Thanks for the fast response! Kudos!
