### ISSUE TITLE
Helm chart tarball in release

### ISSUE THREAD

**Issue by patrick-stephens** [fluent/fluent-operator#230]
Make a tarball for the Helm chart and add it to the release - then people can do a `helm install <URL>` directly rather than having to clone the git repo. This can be done with a simple action: https://github.com/helm/chart-releaser-action

An example is here: https://github.com/couchbase-partners/helm-charts/releases/tag/couchbase-operator-2.2.301

https://github.com/helm/helm/pull/9482 is in the works to support helm install direct from a git repo but not ready yet.

**Comment by benjaminhuo** [comment]
Good idea @wenchajun would you help on this?

**Comment by wenchajun** [comment]
OK, I will do it at once.

**Comment by patrick-stephens** [comment]
The Couchbase chart workflows are here if it helps: https://github.com/couchbase-partners/helm-charts/tree/master/.github/workflows

Specifically: https://github.com/couchbase-partners/helm-charts/blob/master/.github/workflows/publish-ci.yml#L66-L69

**Comment by zhu733756** [comment]
Great, we will integrate this tool later.

**Comment by patrick-stephens** [comment]
Looks good in the release now, we should update the docs to use the tarball now: https://github.com/fluent/fluent-operator#deploy-fluent-operator-with-helm

**Comment by benjaminhuo** [comment]
agree @zhu733756

**Comment by Startouf** [comment]
I believe this was done and can be closed ?
