### ISSUE TITLE
generated clientset is not present anymore in this repo

### ISSUE THREAD

**Issue by davidovich** [fluent/fluent-operator#233]
Clientset was added in b95dcb030639e28353bc82cb1998c47e04191180 then removed in 1d5a484558702cc850fe0e3e564046223c473ab0 

Is this expected ? I would like to consume the fluentbit clientset and would have expected to find it in this repo. Should I be looking somewhere else ? Thanks !

**Comment by davidovich** [comment]
The hierarchy is present, but pacakges are empty.

![image](https://user-images.githubusercontent.com/1440370/157975803-902f1160-968b-4158-89db-ef8d5eed4753.png)

**Comment by davidovich** [comment]
Found `api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/fluentbit.go` in https://github.com/fluent/fluent-operator/commit/1d5a484558702cc850fe0e3e564046223c473ab0, but `api/` does not exist anymore.

**Comment by zhu733756** [comment]
Hi, thanks for your feedback, I pull a request for fixing this issue, pls help to review it.
