### ISSUE TITLE
The clientset should not need a namespace for cluster scoped resources

### ISSUE THREAD

**Issue by davidovich** [fluent/fluent-operator#237]
The generated clientset for ClusterInputs (and other types of now (as of 1.0-rc) cluster-bound resources) needs a namespace, but since ClusterInput (et al.) is a cluster scoped resource, the Create fails.

Consider:

```golang
fluentbit, _ := fluentbitAPI.NewForConfig(config)
_, err = fluentbit.ClusterInputs("a-namespace").Create(ctx, "myInputName", metav1.CreateOptions{})
// err.Error() == "the server could not find the requested resource (post clusterinputs.fluentbit.fluent.io)"
// Causes[0]: Type: "UnexpectedServerResponse", Message: "404 page not found"
```

The above fails. It is equivalent to a manual call on the API: 

```
POST /apis/fluentbit.fluent.io/v1alpha2/namespaces/a-namespace/clusterinputs
```

Manually calling the API at non-namespaced path (note the removed namespace):

```
POST /apis/fluentbit.fluent.io/v1alpha2/clusterinputs
```
Succeeds. 

ref: [API concepts](https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-uris).

Please advise as there doesn't seem to be any generated API to create a ClusterInput. Note that I might be "holding it wrong". The Kubebuilder options correctly state scope=Cluster, so something is strange in the generated API.

**Comment by davidovich** [comment]
Thank you for the fantastic support!

**Comment by zhu733756** [comment]
> Thank you for the fantastic support!

No pls, let's make this repo more popular!
