### ISSUE TITLE
Bug: fluentbit operator does not supports 'Time_Key_Nanos' field

### ISSUE THREAD

**Issue by wangxiaoyang-dev** [fluent/fluent-operator#243]
fluent bit's output elasticsearch module supports 'Time_Key_Nanos' field, see below for details:
https://docs.fluentbit.io/manual/v/1.8/pipeline/outputs/elasticsearch#:~:text=dT%25H%3A%25M%3A%25S-,Time_Key_Nanos,-When%20Logstash_Format%20is
but fluentbit operator does not support 'Time_Key_Nanos' field, see below for details:
https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/plugins/output/elasticsearch_types.go#:~:text=type-,Elasticsearch,-struct%20%7B

**Comment by wenchajun** [comment]
Yes, we will be refining this field in the future. Would you like to contribute code?

**Comment by wangxiaoyang-dev** [comment]
Yes. I will try.
