### ISSUE TITLE
Example file not found

### ISSUE THREAD

**Issue by JoseAntonioConde** [fluent/fluent-operator#253]
### Describe the bug

Execute the command for quickstart with fluentbit:

kubectl apply -f https://raw.githubusercontent.com/fluent/fluentbit-operator/release-0.12/manifests/setup/setup.yaml

Returns error:
error: unable to read URL "https://raw.githubusercontent.com/kubesphere/fluentbit-operator/master/manifests/quick-start/quick-start.yaml", server reported 404 Not Found, status code=404

### To Reproduce

Execute:
kubectl apply -f https://raw.githubusercontent.com/fluent/fluentbit-operator/release-0.12/manifests/setup/setup.yaml

### Expected behavior

Create the expected example.

### Your Environment

```markdown
- Fluent Operator version: v0.4.1
- Kubernetes Version: 1.23
```

### How did you install fluent operator?

using the Yaml example: https://raw.githubusercontent.com/fluent/fluentbit-operator/release-0.12/manifests/setup/setup.yaml

### Your Error Log

```shell
error: unable to read URL "https://raw.githubusercontent.com/kubesphere/fluentbit-operator/master/manifests/quick-start/quick-start.yaml", server reported 404 Not Found, status code=404
```

**Comment by wenchajun** [comment]
Thank you very much for your feedback, this looks like an error in the documentation and we will fix it as soon as possible.
