### ISSUE TITLE
Add its shortname for each CRD

### ISSUE THREAD

**Issue by wenchajun** [fluent/fluent-operator#264]
### Is your feature request related to a problem? Please describe.

Now, not every CRD has its corresponding shortname. `fluentd` and `fluentbit` plug-in CRDs do not have a corresponding shortname, can we add a corresponding shortname for them?

### Describe the solution you'd like

We can add the corresponding shortname for each CRD

### Describe alternatives you've considered

The shortname for fluentbit output could perhaps be changed to `fbo`. accordingly, the shortname for fluentd could perhaps be changed to `fdo`.

### Additional context

Initially our treatment of shortname was as follows : https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go#L75

**Comment by benjaminhuo** [comment]
Please list each CRD with its current shortname, and suggested shortname @wenchajun

**Comment by wenchajun** [comment]
| CRD                                         | current | suggest |
| ------------------------------------------- | ------- | ------- |
| fluentbits.fluentbit.fluent.io              | fb      |         |
| clusterfluentbitconfigs.fluentbit.fluent.io | fbc     |         |
| clusterinputs.fluentbit.fluent.io           |         | fbi     |
| clusterfilters.fluentbit.fluent.io          |         | fbf     |
| clusterparsers.fluentbit.fluent.io          |         | fbp     |
| clusteroutputs.fluentbit.fluent.io          |         | fbo     |
| fluentds.fluentd.fluent.io                  | fd      |         |
| fluentdconfigs.fluentd.fluent.io            | fdc     |         |
| clusterfluentdconfigs.fluentd.fluent.io     | cfdc    |         |
| filters.fluentd.fluent.io                   |         | fdf     |
| clusterfilters.fluentd.fluent.io            |         | cfdf    |
| clusteroutputs.fluentd.fluent.io            |         | cfdo    |
| outputs.fluentd.fluent.io                   |         | fdo     |

**Comment by benjaminhuo** [comment]
The cluster crd should have c for shortname like fbi => cfbi

**Comment by benjaminhuo** [comment]
fbc => cfbc

**Comment by wenchajun** [comment]
| CRD                                         | current | suggest |
| ------------------------------------------- | ------- | ------- |
| fluentbits.fluentbit.fluent.io              | fb      |         |
| clusterfluentbitconfigs.fluentbit.fluent.io | fbc     |    cfbc     |
| clusterinputs.fluentbit.fluent.io           |         | cfbi     |
| clusterfilters.fluentbit.fluent.io          |         | cfbf     |
| clusterparsers.fluentbit.fluent.io          |         | cfbp     |
| clusteroutputs.fluentbit.fluent.io          |         | cfbo     |
| fluentds.fluentd.fluent.io                  | fd      |         |
| fluentdconfigs.fluentd.fluent.io            | fdc     |         |
| clusterfluentdconfigs.fluentd.fluent.io     | cfdc    |         |
| filters.fluentd.fluent.io                   |         | fdf     |
| clusterfilters.fluentd.fluent.io            |         | cfdf    |
| clusteroutputs.fluentd.fluent.io            |         | cfdo    |
| outputs.fluentd.fluent.io                   |         | fdo     |

**Comment by benjaminhuo** [comment]
Looks good now
