### ISSUE TITLE
Helm Chart: Add FluentBit Prometheus integration

### ISSUE THREAD

**Issue by hostalp** [fluent/fluent-operator#266]
### Is your feature request related to a problem? Please describe.

Please add the Prometheus support into the Helm Chart just like the https://github.com/fluent/helm-charts/tree/main/charts/fluent-bit (for example) has.
It enables the metrics HTTP server and creates a service resource for it, with optionally using the `prometheus.io` annotations (for the "old" style Prometheus server support), or servicemonitor (monitoring.coreos.com/v1) resource (for the Prometheus Operator support).

### Describe the solution you'd like

Similarly to https://github.com/fluent/helm-charts/tree/main/charts/fluent-bit
- ability to enable the FluentBit metrics HTTP server and create a Service resource for it (optionally with prometheus.io annotations to enable scraping)
- ability to create the ServiceMonitor resource for the above service to enable discovery by the Prometheus Operator

Additionally
- ability to enable the Grafana dashboard

### Describe alternatives you've considered

As a workaround, one can currently try to modify the existing default `ClusterFluentBitConfig` resource to enable the metrics HTTP server (similarly to https://github.com/fluent/fluent-operator#monitoring), then create the required service and servicemonitor resources manually to get the Prometheus Operator integration to work. I haven't tried that however (but I believe it should work).

For the Grafana dashboard there isn't direct support, so only adding it externally would be an option.

### Additional context

I don't currently use the Fluentd so the above is related to the FluentBit only.
However something similar may be needed for the Fluentd as well if that one is also able to provide Prometheus metrics.

**Comment by FeynmanZhou** [comment]
Thanks for this feature request. I remember @benjaminhuo @wenchajun also mentioned the Prometheus metrics support for the Helm chart in the Fluent Operator roadmap. Maybe we could collaborate to make it happen.

**Comment by wenchajun** [comment]
We have completed the relevant development, refer to this https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/values.yaml#L122
