### ISSUE TITLE
Helm Chart: Incorrect resources values for fluentd

### ISSUE THREAD

**Issue by hostalp** [fluent/fluent-operator#271]
### Describe the bug

The `fluentd-fluentd.yaml` file contains the following:
```
  resources:
  {{- toYaml .Values.fluentbit.resources | nindent 4  }}
```
Clearly the values should come from `fluentd.resources` and not `fluentbit.resources`

### To Reproduce

Install the Helm chart with different settings of `fluentd.resources` and `fluentbit.resources`
Verify that the fluentd is actually running with the fluentbit resources settings instead of the fluentd ones:
`kubectl get statefulset fluentd -o jsonpath={.spec.template.spec.containers[*].resources}`
`kubectl get pods fluentd-0 -o jsonpath={.spec.containers[*].resources}`

### Expected behavior

`fluentd.resources` settings should be used

### Your Environment

```markdown
- Fluent Operator version: Helm Chart 1.0.0
- Container Runtime: docker, Kubernetes 1.20.11
```

### Your Error Log

```shell
N/A
```

**Comment by benjaminhuo** [comment]
@hostalp Thanks for reporting this issue.
Would you like to create a PR to fix this?
