### ISSUE TITLE
how set log_level of fluentbit ? 

### ISSUE THREAD

**Issue by zhuw0312** [fluent/fluent-operator#275]
### Describe the bug

installed fluent-operator in only fluent-bit mode，but can not set log_level.
the default log_level is info which can not debug.

### To Reproduce

i want set log_level=debug.

### Expected behavior

i want set log_level=debug.

### Your Environment

```markdown
- Fluent Operator version: v1.0.0
- Container Runtime: docker
- Operating system: CentOS Linux release 7.5.1804 (Core)
- Kernel version: 3.10.0-862.3.3.el7.x86_64
```

### How did you install fluent operator?

kubectl apply set-up.yaml

### What happened?

level=info msg="Fluent bit started"
Fluent Bit v1.8.11
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

### Your Error Log

```shell
i want set log_level=debug.
```

### Additional context

i want set log_level=debug.

**Comment by wenchajun** [comment]
In fluentbit its configuration is this : https://docs.fluentbit.io/manual/v/1.8/pipeline/inputs/syslog#fluent-bit-configuration
You can configure these parameters in the fluent-operator:
https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go#L35
like this
```
spec:
  service:
    parsersFile: parsers.conf
    logLevel : debug
....
```

**Comment by zhuw0312** [comment]
oh , tks very much.
i set log_Level: DEBUG，not work.
