### ISSUE TITLE
how use rename_key on ClusterFilter

### ISSUE THREAD

**Issue by buxiaomo** [fluent/fluent-operator#281]
### Describe the bug

input like

```
{"ip":"1.1.1.1"}
```

output like

```
{"ipaddr":"1.1.1.1"}
```

configuration file like

```
<filter kubernetes.var.log.containers.**.log>
  @type rename_key
  enable_ruby true
  rename_rule1 ip ipaddr
</filter>
```

### To Reproduce

how to use rename_key on ClusterFilter

### Expected behavior

how to use rename_key on ClusterFilter

### Your Environment

```markdown
- Fluent Operator version:v1.0.0
- Container Runtime:docker
- Operating system:CentOS Linux release 7.9.2009 (Core)
- Kernel version:5.4.190-1.el7.elrepo.x86_64
```

### How did you install fluent operator?

kubectl kustomize manifests/setup/ | kubectl apply -f -

### Your Error Log

```shell
how to use rename_key on ClusterFilter
```

**Comment by wenchajun** [comment]
Does this plugin refer to fluentd's plugin? fluentd's plugin may not be perfect, more plugin integrations are in development, you can try this one: https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/plugins/filter/record_transformer.go

**Comment by buxiaomo** [comment]
thk
