### ISSUE TITLE
Fluentbit integrated OpenSearch plugin

### ISSUE THREAD

**Issue by wenchajun** [fluent/fluent-operator#284]
### Is your feature request related to a problem? Please describe.

Fluent Bit is a graduated sub-project under the Cloud Native Computing Foundation (CNCF) Fluentd project umbrella. Similar to the parent project, Fluent Bit has hundreds of integrations to common tools such as Kafka, Syslog, Loki, as well as to services like Datadog, Splunk, and New Relic. Now with Fluent Bit 1.9, OpenSearch is included as part of the binary package.
But the fluentbit in the fluent-operator does not have an associated crd, for which we need to integrate the OpenSearch plugin.

### Describe the solution you'd like

The specific writing method can be referred to: https://github.com/fluent/fluent-operator/tree/master/apis
In the meantime, we can refer to this article: https://opensearch.org/blog/technical/2022/03/getting-started-with-fluent-bit-and-opensearch/
The profile transcoding in `secret` should look something like this:
```
[OUTPUT]
   Name opensearch
   Match *
   Host 192.168.2.3
   Port 9200
   Index my_index
   Type my_type
```

### Describe alternatives you've considered

Since OpenSearch is similar to Elasticsearch,for the CRD writing of the OpenSearch plugin, we can specifically draw on this document：
https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/plugins/output/elasticsearch_types.go

**Comment by mangoGoForward** [comment]
I'd like to tackle it.

**Comment by wenchajun** [comment]
> I'd like to tackle it.
Thank you. If you have any questions, please feel free to talk.

**Comment by benjaminhuo** [comment]
> I'd like to tackle it.

Great!
