### ISSUE TITLE
Fluentd integrated OpenSearch plugin

### ISSUE THREAD

**Issue by wenchajun** [fluent/fluent-operator#285]
### Is your feature request related to a problem? Please describe.

For users not familiar with Fluentd, one of its strengths is the ability to collect data from multiple sources through plugins and add formatting, processing, or enrichment before sending it out to multiple outputs. There are over 500+ community plugins for Fluentd that can read data including enterprise staples like Kafka, as well as data heavy backends like Hadoop and MongoDB.
But the fluentd in the fluent-operator does not have an associated CRD, for which we need to integrate the OpenSearch plugin.

### Describe the solution you'd like

The specific writing method can be referred to: https://github.com/fluent/fluent-operator/tree/master/apis
In the meantime, we can refer to this article: https://www.opensearch.org/blog/technical/2022/02/getting-started-with-fluentd-and-opensearch/
The profile transcoding in secret should look something like this:
```
<match dummy>
@type opensearch
host localhost
port 9200
index_name fluentd
</match>

```

### Describe alternatives you've considered

Since OpenSearch is similar to Elasticsearch, for the CRD writing of the OpenSearch plugin, we can specifically draw on this document：
https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/plugins/output/es.go

### Additional context

This one may be a bit harder than fluentbit integration, as it is necessary to ensure the presence of OpenSearch related plugins in the fluentd.

**Comment by jett-deng** [comment]
I'd like to tackle this issue.

**Comment by benjaminhuo** [comment]
@jett-deng That's great, thanks!
