### ISSUE TITLE
Modify the input mechanism of fluentd

### ISSUE THREAD

**Issue by wenchajun** [fluent/fluent-operator#305]
### Is your feature request related to a problem? Please describe.

Because we use the label-router component, this provides great convenience for the implementation of multi-tenant isolation. However, it currently does not receive logs from messages such as HTTP, and we are designing a better solution to this problem.

### Describe the solution you'd like

For the `http`  plugin, we just need to do the following configuration to achieve it.
```
<source>
  @type http
  port 9880
  bind 0.0.0.0
  body_size_limit 32m
  keepalive_timeout 10s
</source>
```

### Describe alternatives you've considered

Is it possible to set up two ways for the user to switch the input source based on a field in CRD? Or does anyone have a better way?

**Comment by benjaminhuo** [comment]
maybe it's not only HTTP, all non-k8s format logs received from the network need to be handled.
label_rounter only works for k8s format logs
