### ISSUE TITLE
Cut New Release That Includes OpenSearch

### ISSUE THREAD

**Issue by frankgreco** [fluent/fluent-operator#308]
### Is your feature request related to a problem? Please describe.

it appears that opensearch has been merged. Can we get `v1.0.3` cut?

### Describe the solution you'd like

n/a

### Describe alternatives you've considered

n/a

**Comment by wenchajun** [comment]
Although we are currently using fluentbit 1.8.11, users can manually upgrade fluentbit's version. Is there any reason why it must be removed?

**Comment by frankgreco** [comment]
I meant an new operator version that includes the k8s control plane changes for this plugin

**Comment by frankgreco** [comment]
And cut as in "create a new release" not remove it. Sorry for the lingo

**Comment by benjaminhuo** [comment]
That's a new feature added, so the new release could be v1.1.0

**Comment by frankgreco** [comment]
That works too 🙂

**Comment by frankgreco** [comment]
@benjaminhuo when would you be able to create the new tag/release/assets?

**Comment by benjaminhuo** [comment]
@frankgreco Hopefully in a week

**Comment by benjaminhuo** [comment]
v1.1.0 has been released, close this issue.
