### ISSUE TITLE
Incorrect Value for KeyDoesNotExist

### ISSUE THREAD

**Issue by frankgreco** [fluent/fluent-operator#309]
### Describe the bug

[`Condition.KeyDoesNotExist`](https://github.com/fluent/fluent-operator/blob/0988420656d2037c731f6343ffbbf61f2fdaac36/apis/fluentbit/v1alpha2/plugins/filter/modify_types.go#L28) takes `map[string]string`. However, the [docs](https://docs.fluentbit.io/manual/pipeline/filters/modify) only have one param. I think this should be similar to `KeyExists`? 

Is this a bug? If so I'll submit a PR. If not, what is the proper value for the map value? Also, can I work around it by setting the value to the empty string?

Note there are tests asserting what I believe to be the wrong thing [here](https://github.com/fluent/fluent-operator/blob/0988420656d2037c731f6343ffbbf61f2fdaac36/apis/fluentbit/v1alpha2/plugins/filter/modify_types_test.go#L59). Or at least they contradict the FluentBit docs.

### To Reproduce

n/a

### Expected behavior

n/a

### Your Environment

```markdown
- Fluent Operator version: master
- Container Runtime: n/a
- Operating system: n/a
- Kernel version: n/a
```

### Your Error Log

```shell
n/a
```

**Comment by benjaminhuo** [comment]
@frankgreco Thanks for reporting this, and we'll take a look at this

**Comment by wenchajun** [comment]
This is because `fluentbit` 1.7 and earlier versions had two values, with the upgrade of `fluentbit` the value of this parameter is only one value. You can see [here](https://docs.fluentbit.io/manual/v/1.7/pipeline/filters/modify#conditions).

**Comment by frankgreco** [comment]
@wenchajun It makes sense then for backwards compatibility. However, anyone that is isn't familiar with FluentBit v1.7 or earlier (which I assume is most people) will be confused. Perhaps there could be a `KeyDoesNotExistLegacy` or something that makes it less confusing (I guess this would be a breaking change so not ideal)? At a minimum a code comment describing what to do for earlier versions (empty string value).

Also, what is the end of life timeline for FluentBit versions. When will 1.7 be EOL?

**Comment by frankgreco** [comment]
@wenchajun what do you think?

**Comment by agup006** [comment]
1.7 and 1.8 are already EOL, I like the suggestion of KeyDoesNotExistLegacy or an alternative. Do we need to raise in Fluent Bit main repo?

**Comment by benjaminhuo** [comment]
> 1.7 and 1.8 are already EOL, I like the suggestion of KeyDoesNotExistLegacy or an alternative. Do we need to raise in Fluent Bit main repo?

The Condition.KeyDoesNotExist has been changed since v1.8. 
I think it makes sense to change it accordingly in fluent operator because now fluent operator supports v1.8+ and we're going to release a new version to support v1.9.

We needn't to `KeyDoesNotExistLegacy` for now because 1.7 is EOL.
@frankgreco would you create a PR for this?

**Comment by frankgreco** [comment]
Yes. Btw I think there are a few other instances of this. We can apply the same fix as they are found. Btw, since this is a breaking change. I'll let you guys figure out how you want to handle the semver

**Comment by benjaminhuo** [comment]
We're going to release 1.10

**Comment by frankgreco** [comment]
I meant breaking change for this repo, the operator. We should probs audit the rest of the process in `apis/fluentbit` where this same issues applies and fix them before bumping the version.

**Comment by benjaminhuo** [comment]
@frankgreco we might need to add CRD conversion for changes like this https://book.kubebuilder.io/multiversion-tutorial/conversion-concepts.html https://book.kubebuilder.io/multiversion-tutorial/conversion.html

An example is here https://github.com/OpenFunction/OpenFunction/blob/main/apis/core/v1alpha2/function_webhook.go
https://github.com/OpenFunction/OpenFunction/blob/main/apis/core/v1alpha2/function_conversion.go

**Comment by frankgreco** [comment]
@benjaminhuo don't we need to decide on what the plan is to your comment before that PR is merged? Anyone that pulls `latest` will now run into errors and must upgrade all CRDs using that filter. 

> I mean we may introduce a new CRD version v1beta1 and support conversion between v1beta1 and current v1alpha2 if there're quite a few changes like this

I think we need to go with this change. Regardless of whether or not there are quite a few changes like this, I think the disruption just this change alone causes is bad.

I think we should track v1beta1 or v1alpha3 and aggregate a batch of changes to go in.

**Comment by wenchajun** [comment]
I think each version update will add or modify a part of the plug-in (including some bugfix). So each upgrade will result in a redeployment of crd. And with fluentbit 1.7 eol, lower versions of fluentbit are no longer supported.

**Comment by benjaminhuo** [comment]
@frankgreco the current k8s log processing pipeline doesn't use this functionality of the modify filter plugin and we haven't received an issue-reporting of his bug(The current FB version is v1.8.x+, which is incompatible with the old modify filter setting). Furthermore, v1.7.x has reached its EOL and the latest operator release will ship with recent FB version

So we may not upgrade the CRD version this time.

**Comment by benjaminhuo** [comment]
OK, I understood your concern now.
Let's revert this PR and prepare to upgrade the CRD version and add CRD conversion to it.

**Comment by benjaminhuo** [comment]
The PR has been reverted and let's reopen this issue to continue to work on it.

**Comment by benjaminhuo** [comment]
We want to include your previous PR because the current filter plugin setting `KeyDoesNotExist` is still for fluent bit v1.7. Although the default image shipped with the operator is already v1.8.

We might release v1alpha3  CRDs maybe after adding the custom plugin CRD mentioned in https://github.com/fluent/fluent-operator/issues/301#issuecomment-1152362843

**Comment by frankgreco** [comment]
> We might release v1alpha3 CRDs maybe after adding the custom plugin CRD mentioned in https://github.com/fluent/fluent-operator/issues/301#issuecomment-1152362843

Perhaps then to get started we can do this
```
- you create a branch called v1alpha3 (I don't believe I have access)
- we merge PRs into that branch until we'll ready to release it
- I'll reopen my PR against that branch

**Comment by benjaminhuo** [comment]
https://github.com/fluent/fluent-operator/tree/v1alpha3 
@frankgreco v1alpha3 branch created

**Comment by frankgreco** [comment]
@benjaminhuo Thank you! I'm at Snowflake Summit this week but I'll PR against that branch (along with all of the new v1alpha3 boilerplate) when I get a chance.

**Comment by joshuabaird** [comment]
This issue is being closed due to inactivity.  Please re-open a new issue if it is still relevant.
