### ISSUE TITLE
Add Loki output support for Fluentd

### ISSUE THREAD

**Issue by tanmay-bhat** [fluent/fluent-operator#310]
### Is your feature request related to a problem? Please describe.

Yes, since loki is easy and simple to ingest logs, it would be great if the loki plugin is available for fluentd

### Describe the solution you'd like

Loki output plugin should exist for fluend similar to fluent-bit

### Describe alternatives you've considered

None

**Comment by JetSquirrel** [comment]
I'd like to tackle it.

**Comment by benjaminhuo** [comment]
@JetSquirrel Great!

**Comment by Fatpa** [comment]
I have already finished this job, and could you assign it to me?
