### ISSUE TITLE
Annotation Support

### ISSUE THREAD

**Issue by frankgreco** [fluent/fluent-operator#311]
### Is your feature request related to a problem? Please describe.

There is no way to inject annotations into FluentBit DaemonSet pods. This is problematic as I cannot add the necessary annotations to my Prometheus scraper to scape the metrics that these pods expose.

### Describe the solution you'd like

Allow the user to add them [here](https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/fluentbit_types.go#L30) and then inject them in.

### Describe alternatives you've considered

I think the only way to do this would be to write my own `MutatingWebhook` or `Controller` which would be a lot of work for something that I think should be configurable.

**Comment by benjaminhuo** [comment]
That's a good requirement, would you help to add this? @frankgreco

**Comment by frankgreco** [comment]
Yea you can assign it to me.
