### ISSUE TITLE
fluent bit CRD doesn't accomodate securityContext

### ISSUE THREAD

**Issue by perezjasonr** [fluent/fluent-operator#320]
### Is your feature request related to a problem? Please describe.

We were considering trying out the fluent bit operator instead of a more basic fluent bit manifest. but if the CRD for fluent bit (or fluentd) doesn't give access to the securityContext the deployment will get blocked in our environment. The raw manifest obviously allowed this but the operator+CRD does not, short of patching it after the fact.

### Describe the solution you'd like

in the CRD (or additionally in helm) a securityContext section like so

securityContext: []

### Describe alternatives you've considered

patching it after the fact, or just using raw manifest/kustomize (direct fluentbit kustomize not kustomize to deploy the operator)

**Comment by benjaminhuo** [comment]
That's a good requirement.
We can start adding this to fluentbit CRDs. @wenchajun @wanjunlei 
Also, you're more than welcome to submit a PR for this as well.
