### ISSUE TITLE
Add OpenTelemetry & Node Exporter Metrics plugins for Fluent Bit

### ISSUE THREAD

**Issue by benjaminhuo** [fluent/fluent-operator#325]
### Is your feature request related to a problem? Please describe.

The [OpenTelemetry output plugin](https://docs.fluentbit.io/manual/pipeline/outputs/opentelemetry) allows you to take metrics from Fluent Bit and submit them to an OpenTelemetry HTTP endpoint.

The [OpenTelemetry output plugin](https://docs.fluentbit.io/manual/pipeline/outputs/opentelemetry) plugin works together with the [Node Exporter Metrics](https://docs.fluentbit.io/manual/pipeline/inputs/node-exporter-metrics) input plugin, so the [Node Exporter Metrics](https://docs.fluentbit.io/manual/pipeline/inputs/node-exporter-metrics) input plugin should be added together with the [OpenTelemetry output plugin](https://docs.fluentbit.io/manual/pipeline/outputs/opentelemetry) 

And the log and tracing will be added in the future as well to enable Fluent Bit as the universal observability agent to collect logs/metrics/tracing data and send these to OpenTelemetry

### Describe the solution you'd like

NA

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by mangoGoForward** [comment]
I can tackle it

**Comment by benjaminhuo** [comment]
That's great! @mangoGoForward
