### ISSUE TITLE
Issue templates: remove some verbose steps in issues template

### ISSUE THREAD

**Issue by mangoGoForward** [fluent/fluent-operator#328]
### Is your feature request related to a problem? Please describe.

We have two issue templates: [bug report](https://github.com/fluent/fluent-operator/blob/master/.github/ISSUE_TEMPLATE/bug_report.yaml) and [feature request], but some steps maybe too verbose to let users confused, and we could simplified steps which can let user contribute easily.
Like "What happened" and "Your Error Log" steps in bug report template, this message may already described in "Describe the bug" step,  "Describe alternatives you've considered" step in Feature request template, those messages could described in "Describe the solution you'd like" step.

### Describe the solution you'd like

Remove "What happened" and "Your Error Log" steps in bug report template and "Describe alternatives you've considered" step in Feature request template.

### Describe alternatives you've considered

Same as the "Describe the solution you'd like" step

**Comment by benjaminhuo** [comment]
Agree
