### ISSUE TITLE
Add SSL/TLS settings feature for fluentd output Elasticsearch

### ISSUE THREAD

**Issue by phamgiabao1398** [fluent/fluent-operator#418]
### Is your feature request related to a problem? Please describe.

My elasticsearch cluster endpoints using HTTPS with self-sign certificate. I try to use config "ssl_verify false" of fluentd but the crd doesn't support it.

### Describe the solution you'd like

Add SSL/TLS settings feature for fluentd output Elasticsearch.

**Comment by nelsontleidos** [comment]
would love to have "ssl_verify" setting also for development environments.

**Comment by allanian** [comment]
+1

**Comment by benjaminhuo** [comment]
> @benjaminhuo, Can I work on this?
@husnialhamdani 
Yes, you're well come to work on this.
