### ISSUE TITLE
Trivial bug

### ISSUE THREAD

**Issue by a13xbr0** [fluent/fluent-operator#451]
### Describe the issue

Doubled (copy-pasted?) 'line_format': [link](https://github.com/fluent/fluent-operator/blob/d43a36899acf61b8416d38a1b061f3781931c3fb/apis/fluentd/v1alpha1/plugins/output/types.go#L550) 

### To Reproduce

Try to configure fluentd Loki output with lineFormat & autoKubernetesLabels parameters

### Expected behavior

Should work as described in docs

### Your Environment

```markdown
- Fluent Operator version:master
- Container Runtime: docker
- Operating system:
- Kernel version:
```

**Comment by wenchajun** [comment]
Thanks, this is indeed a problem and we will fix it, would you be willing to contribute code to fix it?

**Comment by wenchajun** [comment]
I see that the issue is currently fixed, so I closed the issue, and if you have any questions, feel free to open it again.
