### ISSUE TITLE
Add the fluent-operator chart to the fluent helm-charts repo

### ISSUE THREAD

**Issue by wenchajun** [fluent/fluent-operator#460]
### Is your feature request related to a problem? Please describe.

It is necessary to add the `fluent-operator` to the `fluent` [helm chart](https://fluent.github.io/helm-charts) for uniformity and user-friendliness.

### Describe the solution you'd like

Add the fluent-operator chart to the https://fluent.github.io/helm-charts repo

**Comment by pierluigilenoci** [comment]
@momoXD007 @benjaminhuo @chengdehao @Brightside56 are there any chances of seeing this happen anytime soon? 🙏🏻

**Comment by benjaminhuo** [comment]
@wenchajun Would you help to create a PR to add fluent operator's helm chart to https://github.com/fluent/helm-charts

**Comment by benjaminhuo** [comment]
> @benjaminhuo @Brightside56 are there any chances of seeing this happen anytime soon? 🙏🏻

@pierluigilenoci https://github.com/fluent/helm-charts/pull/299 we've created a PR to merge the helm chart of fluent operator to the fluent's official repo . @patrick-stephens @agup006

**Comment by pierluigilenoci** [comment]
@benjaminhuo cool!
