### ISSUE TITLE
help request: aws opensearch configuration

### ISSUE THREAD

**Issue by haarchri** [fluent/fluent-operator#464]
### Describe the issue

did you guys have a documentation to connect to `aws opensearch` an easy way with `ClusterOutput` ?

**Comment by benjaminhuo** [comment]
@haarchri hope these can help:

https://github.com/fluent/fluent-operator/blob/master/docs/plugins/fluentbit/clusteroutput/opensearch.md
https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/templates/fluentbit-output-opensearch.yaml

**Comment by haarchri** [comment]
yes thanks
