### ISSUE TITLE
operator support for fluentd kinesis/cloudwatch plugins

### ISSUE THREAD

**Issue by jseutter** [fluent/fluent-operator#487]
### Is your feature request related to a problem? Please describe.

I have fluent operator enhanced to support using the fluentd kinesis plugin and am working on cloudwatch plugin support.  Is there interest in having this added to the main codebase, or was there a conscious decision to limit the fluentd plugins that are supported?

### Describe the solution you'd like

.

**Comment by wenchajun** [comment]
Yes, we will be integrating more plugins in the future, would you be interested in getting involved?

**Comment by jseutter** [comment]
I am interested in getting involved.  I'll clean up my changes and create a pull request.

**Comment by benjaminhuo** [comment]
> I am interested in getting involved. I'll clean up my changes and create a pull request.

That's great
