### ISSUE TITLE
help request: documentation description mismatch for flushThreadCount

### ISSUE THREAD

**Issue by samanthacastille** [fluent/fluent-operator#489]
### Describe the issue

The `flushThreadCount` buffer flushing parameter is described as two totally different things in the [github docs](https://github.com/fluent/fluent-operator/blob/master/docs/plugins/fluentd/common/buffer.md) versus the [site docs](https://docs.fluentd.org/configuration/buffer-section#buffering-parameters).  

Github docs: 
flushThreadCount | The sleep interval (seconds) for threads to wait for the next flush try(when no chunks are waiting) | *string

Site docs:
flush_thread_count [integer]
The number of threads to flush/write chunks in parallel

This discrepancy is very confusing when trying to fine-tune the config parameters for high log volumes.

**Comment by wenchajun** [comment]
https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/plugins/common/buffer_types.go#L241
This should be a writing error, for the same variables the official documentation should prevail, would you be interested in submitting a pr to change it?
