### ISSUE TITLE
bug: operator installed with helm oomkilled

### ISSUE THREAD

**Issue by wigust** [fluent/fluent-operator#495]
### Describe the issue

The default value of operator.resources.limits.memory 30Mi is too low, Kubernetes kills the pod with oomkilled error.

I increased operator.resources.limits.memory to a random value 60Mi as a workaround.

### To Reproduce

Install fluent-operator v1.7.0 with Helm.
Get a OOMKilled error in operator pod.

### Expected behavior

No OOMKilled issue.

### Your Environment

```markdown
- Fluent Operator version: v1.7.0
- Container Runtime: containerd
- Operating system: NixOS 22.11
- Kernel version: 5.15.78
```

### How did you install fluent operator?

[helm chart v1.7.0](https://github.com/fluent/fluent-operator/releases/download/v1.7.0/fluent-operator.tgz)

### Additional context

htop output:
```
    PID USER       PRI  NI  VIRT   RES   SHR S  CPU%▽MEM%   TIME+  Command
 611587 65532       20   0  730M 49716 24428 S   0.0  0.1  1:15.24 /manager
```

**Comment by wenchajun** [comment]
Yes, this parameter can be turned up a bit, would you like to contribute a PR for this?
