### ISSUE TITLE
feature/fluent-bit-watcher: max time parameter to wait for FluentBit to terminate, SIGKILL on timeout

### ISSUE THREAD

**Issue by jjsiv** [fluent/fluent-operator#510]
### Is your feature request related to a problem? Please describe.

For perspective: at my org we are running around 900 fluent-bit pods with Fluent Operator in a cluster.
I've noticed that sometimes when configuration changes and fluent-bit-watcher sends SIGTERM to fluent-bit, fluent-bit will  attempt to shutdown but occasionally will hang on one of the steps. It will then never finish terminating and the process will hang indefinitely in the pod until it is manually killed and recreated.
Out of 900 pods being restarted, it will only happen to some of them (seemingly random), most will terminate successfully and get started again by fluent-bit-watcher as intended. I've not found clear steps to reproduce this issue, unfortunately.

### Describe the solution you'd like

The above problem obviously seems to be more related to FluentBit itself rather than fluent-bit-watcher but I'd like to propose a feature in the fluent-bit-watcher:
an optional parameter for setting maximum time to wait for FluentBit to gracefully terminate before killing it.

I've been experimenting a bit with this already so I could potentially open a PR sometime soon.
Any thoughts?

**Comment by wenchajun** [comment]
This looks like a good idea. Looking forward to your pr.

**Comment by benjaminhuo** [comment]
> The above problem obviously seems to be more related to FluentBit itself rather than fluent-bit-watcher but I'd like to propose a feature in the fluent-bit-watcher: an optional parameter for setting maximum time to wait for FluentBit to gracefully terminate before killing it.
> 
> I've been experimenting a bit with this already so I could potentially open a PR sometime soon. Any thoughts?

This sounds valuable. Your contribution to fluent-bit-watcher is more than welcome
@wanjunlei any comments?
