### ISSUE TITLE
Namespaced FluentBit CRs, generic custom plugin field for Fluentd CRs

### ISSUE THREAD

**Issue by adiforluls** [fluent/fluent-operator#521]
### Is your feature request related to a problem? Please describe.

Hi, was looking at fluent-operator. It is a promising project and a flexible product! There are a few enhancements I think are important though:

- **FluentBit**: 

  1. **Namespaced CRs for FluentBit**: I really like the namespace level CRs for Fluentd to process logs coming out of a namespace. I'd like to see something similar for FluentBit as well, namely a namespace level FluentBitConfig, Filter and Output (Input as well if it makes sense). The reason here is that with FluentBit only mode, it feels like I'm missing out on an important feature and can't process logs at namespace level. Unless there's a very good reason to have only cluster-level configurations for FluentBit, I think this should be done.
  2. Match ClusterFluentBitConfig by label instead of name.

- **Fluentd**: 

    **Generic custom plugin type for Fluentd**: Just like for FluentBit Input/Filter/Output resources, a custom plugin field where one can specify raw configurations of Fluentd plugins that have not been implemented yet. It's also important in my opinion.

### Describe the solution you'd like

- Namespaced FluentBitConfig, Input/Filter/Output (or Filter/Output) for FluentBit Daemonset. The FluentBitConfig can match to namespace and cluster-level resources (behaviour identical to FluentdConfig).
- Match FluentBitConfig via labels for multiple log routing paths.
- Generic custom plugin field for Fluentd Filter and Output.

### Additional context

Note: Open to discussion on the above listed enhancements. If there's an agreement on at-least one of these enhancements, would you guys be willing to accept contributions? I'd like to know the contribution guidelines as well.

**Comment by benjaminhuo** [comment]
> 1. **Namespaced CRs for FluentBit**: I really like the namespace level CRs for Fluentd to process logs coming out of a namespace. I'd like to see something similar for FluentBit as well, namely a namespace level FluentBitConfig, Filter and Output (Input as well if it makes sense). The reason here is that with FluentBit only mode, it feels like I'm missing out on an important feature and can't process logs at namespace level. Unless there's a very good reason to have only cluster-level configurations for FluentBit, I think this should be done.

@adiforluls It's nice to discuss the clustered and namespaced CRD of FluentBit.
I have an explanation in https://github.com/fluent/fluent-operator/issues/516#issuecomment-1400276640:
`FluentBit is namespaced CRD which controls the namespaced Fluent Bit Daemonset.
ClusterInput, ClusterParser, ClusterFilter, and ClusterOutput are all cluster-wide CRDs, this is because FluentBit is acting as a global agent to collect logs on each K8s node which requires cluster-wide privileges.`

Fluentd can receive logs from the global fluentbit daemonset and thus it can handle logs globally or locally in a namespace.
We use an excellent fluentd plugin https://github.com/banzaicloud/fluent-plugin-label-router to route logs to different namespaces and this plugin also makes it possible to route logs for multiple namespaces(each fluentdConfig or clusterFluentdConfig is a separate pipeline), but fluentbit doesn't have such a plugin.

We're adding a new mode called `FluentBit Collector` for fluentbit  to receive logs from network (not from the k8s node itself) in https://github.com/fluent/fluent-operator/pull/484#issuecomment-1338667600 and it makes sense to change it to namespaced CRDs @wanjunlei @wenchajun

**Comment by benjaminhuo** [comment]
> * **Generic custom plugin type for Fluentd**: Just like for FluentBit Input/Filter/Output resources, a custom plugin field where one can specify raw configurations of Fluentd plugins that have not been implemented yet. It's also important in my opinion

Adding custom plugins for fluentd might be a good idea and @adiforluls you're welcome to work on this!
You can refer to the design of fluentbit customPlugin: https://github.com/fluent/fluent-operator/blob/master/docs/best-practice/custom-plugin.md

**Comment by adiforluls** [comment]
> > 1. **Namespaced CRs for FluentBit**: I really like the namespace level CRs for Fluentd to process logs coming out of a namespace. I'd like to see something similar for FluentBit as well, namely a namespace level FluentBitConfig, Filter and Output (Input as well if it makes sense). The reason here is that with FluentBit only mode, it feels like I'm missing out on an important feature and can't process logs at namespace level. Unless there's a very good reason to have only cluster-level configurations for FluentBit, I think this should be done.
> 
> @adiforluls It's nice to discuss the clustered and namespaced CRD of FluentBit. I have an explanation in [#516 (comment)](https://github.com/fluent/fluent-operator/issues/516#issuecomment-1400276640): `FluentBit is namespaced CRD which controls the namespaced Fluent Bit Daemonset. ClusterInput, ClusterParser, ClusterFilter, and ClusterOutput are all cluster-wide CRDs, this is because FluentBit is acting as a global agent to collect logs on each K8s node which requires cluster-wide privileges.`
> 
> Fluentd can receive logs from the global fluentbit daemonset and thus it can handle logs globally or locally in a namespace. We use an excellent fluentd plugin https://github.com/banzaicloud/fluent-plugin-label-router to route logs to different namespaces and this plugin also makes it possible to route logs for multiple namespaces(each fluentdConfig or clusterFluentdConfig is a separate pipeline), but fluentbit doesn't have such a plugin.
> 
> We're adding a new mode called `Collector` for fluentbit to receive logs from network by deploying a fluentbit statefulset (not from the k8s node itself like the fluentbit daemonset) in [#484 (comment)](https://github.com/fluent/fluent-operator/pull/484#issuecomment-1338667600) and maybe it makes sense to change the collector CRDs to namespaced CRDs @wanjunlei @wenchajun

@benjaminhuo At some point in the future, do you think it's possible to have namespaced CRs/multiple log pipelines for FluentBit Daemonset if there is a plugin, or not if we follow your explanation [here](https://github.com/fluent/fluent-operator/issues/516#issuecomment-1400276640)
If the new FluentBit StatefulSet will have namespaced config CRs, can that idea be extended to the Daemonset also (i.e. without requiring a FluentBit plugin for namespace logging/multiple pipelines)?

**Comment by adiforluls** [comment]
I think FluentBit having cluster level CRs because it's a global agent somewhat makes sense when configured to run in a hybrid FluentBit + Fluentd mode (i.e. a global log forwarder). In case of FluentBit only mode, FluentBit will act as both log collector and aggregator, so I think there's value in being able to configure namespace level logging/multiple logging pipelines for FluentBit Daemonset.

**Comment by adiforluls** [comment]
> > * **Generic custom plugin type for Fluentd**: Just like for FluentBit Input/Filter/Output resources, a custom plugin field where one can specify raw configurations of Fluentd plugins that have not been implemented yet. It's also important in my opinion
> 
> Adding custom plugins for fluentd might be a good idea and @adiforluls you're welcome to work on this! You can refer to the design of fluentbit customPlugin: https://github.com/fluent/fluent-operator/blob/master/docs/best-practice/custom-plugin.md
> 
> The reason we didn't add fluentd custom plugin is that unlike fluentbit, you'll have to [customize the fluentd image](https://github.com/fluent/fluent-operator/blob/master/cmd/fluent-watcher/fluentd/Dockerfile.amd64#L26) to add the plugin before you can use it via custom fluentd plugin.

@benjaminhuo Here's the PR for custom fluentd plugin https://github.com/fluent/fluent-operator/pull/555, please review.

**Comment by benjaminhuo** [comment]
> @benjaminhuo Here's the PR for custom fluentd plugin #555, please review

@adiforluls Great work, thank you!
