### ISSUE TITLE
allow reconcilers to be configurable

### ISSUE THREAD

**Issue by dh185221** [fluent/fluent-operator#525]
### Is your feature request related to a problem? Please describe.

on startup, fluent-manager loads multiple reconcilers as seen here https://github.com/fluent/fluent-operator/blob/master/cmd/fluent-manager/main.go#L106-L152

```
	&controllers.FluentBitConfigReconciler
	&controllers.CollectorReconciler
	&controllers.FluentBitReconciler
	&controllers.FluentdConfigReconciler
	&controllers.FluentdReconciler
```
However, some users won't need all of those depending on their scenario.  For example, if I only use fluent bit then having 	`CollectorReconciler`,`FluentdConfigReconciler` and `FluentdReconciler` running on my cluster is unnecessary.

Also, the docs state there is a "[Fluent bit only](https://github.com/fluent/fluent-operator#overview)" mode and I think this can cause confusion if non fluent-bit controller code is actually running on a cluster. 

### Describe the solution you'd like

A user should be able to specify the reconcilers that they need for their environment.

**Comment by benjaminhuo** [comment]
@wanjunlei @wenchajun what do you think? 
Is this necessary?

**Comment by wanjunlei** [comment]
> @wanjunlei @wenchajun what do you think? Is this necessary?

I think this is a good idea.

**Comment by benjaminhuo** [comment]
In my opinion, K8s's controller manager doesn't have such switches and there're multiple controllers enabled at the same time.

Fluent Operator's controller consumes little resources and what are the benefits of adding such switches?

`Fluent Bit Only` mode means users can deploy fluentbit only with fluent operator, and you can deploy a fluentd whenever it's necessary without restarting fluent operator.

**Comment by dh185221** [comment]
Thanks for the clarification @benjaminhuo . Initially I was hopeful that it would be an easy change to the flags in `cmd/fluent-manager/main.go` but I understand that it's likely more involved than that, especially if the custom resources for all types are deployed to clusters by default. Feel free to close the issue unless you're looking for more feedback from others.

**Comment by benjaminhuo** [comment]
> especially if the custom resources for all types are deployed to clusters by default. Feel free to close the issue unless you're looking for more feedback from others.

Yep, all fluentbit and fluentd CRDs are deployed once you install fluent operator.
Adding a flag to disable/enable a controller is easy, but nothing happens if users create a Fluentd CR after disable fluentd controller which is a bit weird.
