### ISSUE TITLE
Support Azure Output plugins

### ISSUE THREAD

**Issue by sergiomcalzada** [fluent/fluent-operator#547]
### Is your feature request related to a problem? Please describe.

Azure plugins aren't supported in the CRD

### Describe the solution you'd like

Add azure definitions to the CRD

### Additional context

https://docs.fluentbit.io/manual/pipeline/outputs/azure

**Comment by benjaminhuo** [comment]
@sergiomcalzada for currently unsupported plugins, you can use the custom plugin for now: https://github.com/fluent/fluent-operator/blob/master/docs/best-practice/custom-plugin.md

And you're welcome to create an Azure output plugin PR

**Comment by sergiomcalzada** [comment]
I would say that is partially covered, as only covers the "azure-blob" plugin
Supporting other two azure plugins would be great
* Azure Log Analytics: https://docs.fluentbit.io/manual/pipeline/outputs/azure
* Azure Data Explorer: https://docs.fluentbit.io/manual/pipeline/outputs/azure_kusto


Tested Azure Log Analytics with the "custom plugin" and it works
Thanks
