### ISSUE TITLE
Add logLevel option to OpenSearch output plugin

### ISSUE THREAD

**Issue by kaiohenricunha** [fluent/fluent-operator#578]
### Is your feature request related to a problem? Please describe.

I was trying to debug fluentd connection to OpenSearch and noticed that the fluentd clusteroutput CRD doesn`t have logLevel for OpenSearch.

### Describe the solution you'd like

Enable logLevel for OpenSearch on fluentd clusteroutput CRD.

**Comment by benjaminhuo** [comment]
@kaiohenricunha It'll be good if you can create a PR for this!
