### ISSUE TITLE
Add scheme parameter to fluentd-output-opensearch.yaml

### ISSUE THREAD

**Issue by kaiohenricunha** [fluent/fluent-operator#579]
### Is your feature request related to a problem? Please describe.

I noticed the fluentd-output-opensearch resource doesn't render `scheme` parameter as it does with host and port, for example. This is because it is included in the CRD, but not in the template.

### Describe the solution you'd like

Include `scheme` validation on fluentd-output-opensearch.yaml template.

**Comment by benjaminhuo** [comment]
@kaiohenricunha It'll be great if you can create a PR for this!

**Comment by jynolen** [comment]
Can you give a bit more context ? 
Is it related to Helm Chart / Configuration of the CRD / Result of the defintion ?

If you are able to provides snippet of what you are trying to do it could be great for us to reproduce.

Thanks !
