### ISSUE TITLE
bug: missing `make manifests` and `make docs-update` before commit

### ISSUE THREAD

**Issue by antrema** [fluent/fluent-operator#590]
### Describe the issue

I found some discrepancies between code and CRDs description/Documentation:
code [apis/fluentd/v1alpha1/plugins/common/buffer_types.go]:
```
// The number of threads to flush/write chunks in parallel  
// +kubebuilder:validation:Pattern:="^\\d+$"  
FlushThreadCount *string `json:"flushThreadCount,omitempty"  
```
Whereas in CRDs
crds [charts/fluent-operator/crds/fluentd.fluent.io_clusteroutputs.yaml]:
```
flushThreadCount:
description: The sleep interval (seconds) for threads to
wait for the next flush try(when no chunks are waiting)
pattern: ^\d+$
type: string
```

### To Reproduce

launch the commands:
`make manifests`
`make docs-update`

### Expected behavior

No modification after launching these commands

### Your Environment

```markdown
- Fluent Operator version: #N/A
- Container Runtime: #N/A
- Operating system: #N/A
- Kernel version: #N/A
```

### How did you install fluent operator?

#N/A

### Additional context

#N/A

**Comment by wenchajun** [comment]
These don't seem like they should be changed manually, they should be left to change automatically. If you modify them manually, then they will be automatically reset back by the script, won't they?

**Comment by benjaminhuo** [comment]
> // The number of threads to flush/write chunks in parallel  
> // +kubebuilder:validation:Pattern:="^\\d+$"  
> FlushThreadCount *string `json:"flushThreadCount,omitempty"

The following two files should be consistent with the code, the other docs like charts and manifests are all generated based on the following two files. 
https://github.com/fluent/fluent-operator/blob/master/config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml#L113
https://github.com/fluent/fluent-operator/blob/master/config/crd/bases/fluentd.fluent.io_outputs.yaml#L112

The cards in config/crd/bases should be generated by running `make generate` which is included in `make test`, so users should run `make test` everytime they change the crd def code, right? @wanjunlei  

https://github.com/fluent/fluent-operator/blob/master/Makefile#L54

**Comment by antrema** [comment]
@benjaminhuo I didn't make the changes manually, I launched `make manifests` and `make docs-update` to generate the files from the code. All my changes have been obtained by above commands, not manually
