### ISSUE TITLE
RecordModifier is missing some upstream configuration

### ISSUE THREAD

**Issue by jynolen** [fluent/fluent-operator#597]
### Is your feature request related to a problem? Please describe.

Hello.

The current implementation of CRDs does not allow usage of upstream feature 

Currently allows:
- records

- removeKeys

- whitelistKeys

Missing :
- Allowlist_key

- Uuid_key

### Describe the solution you'd like

It could be great to have them implemented

### Additional context

Ref:
- https://github.com/fluent/fluent-operator/blob/master/docs/plugins/fluentbit/clusterfilter/recordmodifier.md
- https://docs.fluentbit.io/manual/pipeline/filters/record-modifier

**Comment by benjaminhuo** [comment]
> The current implementation of CRDs does not allow usage of upstream feature

@jynolen Thanks for reporting this, Is it possible for you to create a PR for this?
