### ISSUE TITLE
Make it possible to turn off fluent-bit/fluentd controllers when it is not used

### ISSUE THREAD

**Issue by Kristian-ZH** [fluent/fluent-operator#612]
### Is your feature request related to a problem? Please describe.

Currently, both controllers (`fluentd` and `fluent-bit`) work together and there is no option to disable one of them even when we do not want to use it. This adds the requirement to install all of the CRDs and to create an RBAC with all of the roles there.

### Describe the solution you'd like

The installation of the fluent operator should have the option to disable one of the controllers.

**Comment by benjaminhuo** [comment]
@Kristian-ZH It'll be great if you can help to make these changes with a PR!
