### ISSUE TITLE
Fluentd envVars to pass environment vars to pod

### ISSUE THREAD

**Issue by kaiohenricunha** [fluent/fluent-operator#636]
### Is your feature request related to a problem? Please describe.

Setting environment variables to the fluentd pod.

### Describe the solution you'd like

A straightforward way to pass environment variables to the fluentd pod, similar to the way we can do with fluentbit pods using [envVars](https://github.com/fluent/fluent-operator/blob/18a36b8616769d2fa0ad93f2f109e3516a42bbd4/config/crd/bases/fluentbit.fluent.io_fluentbits.yaml#L895)

**Comment by chancez** [comment]
https://github.com/fluent/fluent-operator/blob/master/pkg/operator/sts.go#L144-L146 looks like it should work with fluentd as well.

**Comment by kaiohenricunha** [comment]
> https://github.com/fluent/fluent-operator/blob/master/pkg/operator/sts.go#L144-L146 looks like it should work with fluentd as well.

When I asked this question it was still 2.1.0:

https://github.com/fluent/fluent-operator/blob/v2.1.0/pkg/operator/sts.go
