### ISSUE TITLE
bug: fluent-bit CRDs missing when deploying from helm chart 2.1.0

### ISSUE THREAD

**Issue by Waidmann** [fluent/fluent-operator#652]
### Describe the issue

When trying to deploy the fluent operator version 2.1.0 it tries to create resources of kind "Parser.fluentbit.fluent.io" and "Filter.fluentbit.fluent.io" and "Output.fluentbit.fluent.io".
As far as I can tell these CRDs are not included in the 2.1.0 releases but are added in the master branch through this PR: https://github.com/fluent/fluent-operator/pull/621 

```
2023-03-30T08:10:15Z	INFO	Starting EventSource	{"controller": "fluentbit", "controllerGroup": "fluentbit.fluent.io", "controllerKind": "FluentBit", "source": "kind source: *v1alpha2.Filter"}
```

```
2023-03-30T08:10:22Z	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "Filter.fluentbit.fluent.io", "error": "no matches for kind \"Filter\" in version \"fluentbit.fluent.io/v1alpha2\""}
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/source/source.go:143
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.26.3/pkg/util/wait/wait.go:235
k8s.io/apimachinery/pkg/util/wait.poll
	/go/pkg/mod/k8s.io/apimachinery@v0.26.3/pkg/util/wait/wait.go:582
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.26.3/pkg/util/wait/wait.go:547
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/source/source.go:136
```

### To Reproduce

This is my values file:

<details>
	<summary>values.yaml</summary>

	containerRuntime: containerd
	#  If you want to deploy a default Fluent Bit pipeline (including Fluent Bit Input, Filter, and output) to collect Kubernetes logs, you'll need to set the Kubernetes parameter to true
	# see https://github.com/fluent/fluent-operator/tree/master/manifests/logging-stack
	Kubernetes: true
	
	operator:
	  # The init container is to get the actual storage path of the docker log files so that it can be mounted to collect the logs.
	  # see https://github.com/fluent/fluent-operator/blob/master/manifests/setup/fluent-operator-deployment.yaml#L26
	  initcontainer:
	    repository: "docker"
	    tag: "20.10"
	  container:
	    repository: "kubesphere/fluent-operator"
	    tag: "latest"
	    # FluentBit operator resources. Usually user needn't to adjust these.
	  resources:
	    limits:
	      cpu: 100m
	      memory: 60Mi
	    requests:
	      cpu: 100m
	      memory: 20Mi
	  # Specify custom annotations to be added to each Fluent Operator pod.
	  annotations: {}
	  ## Reference to one or more secrets to be used when pulling images
	  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
	  imagePullSecrets: []
	  # - name: "image-pull-secret"
	  # Reference one more key-value pairs of labels that should be attached to fluent-operator
	  labels: {}
	  #  myExampleLabel: someValue
	  logPath:
	    # The operator currently assumes a Docker container runtime path for the logs as the default, for other container runtimes you can set the location explicitly below.
	    # crio: /var/log
	    containerd: /var/log
	
	fluentbit:
	  image:
	    repository: "kubesphere/fluent-bit"
	    tag: "v2.0.9"
	  # fluentbit resources. If you do want to specify resources, adjust them as necessary
	  #You can adjust it based on the log volume.
	  resources:
	    limits:
	      cpu: 500m
	      memory: 200Mi
	    requests:
	      cpu: 10m
	      memory: 25Mi
	  # Specify custom annotations to be added to each FluentBit pod.
	  annotations: {}
	    ## Request to Fluent Bit to exclude or not the logs generated by the Pod.
	    # fluentbit.io/exclude: "true"
	    ## Prometheus can use this tag to automatically discover the Pod and collect monitoring data
	  # prometheus.io/scrape: "true"
	  # Specify additional custom labels for fluentbit-pods
	  labels: {}
	
	  ## Reference to one or more secrets to be used when pulling images
	  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
	  ##
	  imagePullSecrets: [ ]
	  # - name: "image-pull-secret"
	  secrets: []
	  # List of volumes that can be mounted by containers belonging to the pod.
	  additionalVolumes: []
	  # Pod volumes to mount into the container's filesystem.
	  additionalVolumesMounts: []
	
	  # Remove the above empty volumes and volumesMounts, and then set additionalVolumes and additionalVolumesMounts as below if you want to collect node exporter metrics
	  # additionalVolumes:
	  #   - name: hostProc
	  #     hostPath:
	  #       path: /proc/
	  #   - name: hostSys
	  #     hostPath:
	  #       path: /sys/
	  # additionalVolumesMounts:
	  #   - mountPath: /host/sys
	  #     mountPropagation: HostToContainer
	  #     name: hostSys
	  #     readOnly: true
	  #   - mountPath: /host/proc
	  #     mountPropagation: HostToContainer
	  #     name: hostProc
	  #     readOnly: true
	
	  #Set a limit of memory that Tail plugin can use when appending data to the Engine.
	  # You can find more details here: https://docs.fluentbit.io/manual/pipeline/inputs/tail#config
	  #If the limit is reach, it will be paused; when the data is flushed it resumes.
	  #if the inbound traffic is less than 2.4Mbps, setting memBufLimit to 5MB is enough
	  #if the inbound traffic is less than 4.0Mbps, setting memBufLimit to 10MB is enough
	  #if the inbound traffic is less than 13.64Mbps, setting memBufLimit to 50MB is enough
	  input:
	    tail:
	      enable: false
	      refreshIntervalSeconds: 10
	      memBufLimit: 5MB
	      path: "/var/log/containers/*.log"
	      skipLongLines: true
	    systemd:
	      enable: false
	      path: "/var/log/journal"
	      includeKubelet: true
	    nodeExporterMetrics: {}
	    # uncomment below nodeExporterMetrics section if you want to collect node exporter metrics
	  #   nodeExporterMetrics:
	  #     tag: node_metrics
	  #     scrapeInterval: 15s
	  #     path:
	  #       procfs: /host/proc
	  #       sysfs: /host/sys
	
	  #Configure the output plugin parameter in FluentBit.
	  #You can set enable to true to output logs to the specified location.
	  output:
	    #  You can find more supported output plugins here: https://github.com/fluent/fluent-operator/tree/master/docs/plugins/fluentbit/clusteroutput
	    loki:
	      host: https://logs-prod-eu-west-0.grafana.net
	      httpUser:
	        valueFrom:
	          secretKeyRef:
	            name: loki-output
	            key: USER
	      httpPassword:
	        valueFrom:
	          secretKeyRef:
	            name: loki-output
	            key: PASSWORD
	    stdout:
	      enable: true
	
	  #Configure the default filters in FluentBit.
	  # The `filter` will filter and parse the collected log information and output the logs into a uniform format. You can choose whether to turn this on or not.
	  filter:
	    kubernetes:
	      enable: true
	      labels: false
	      annotations: false
	    containerd:
	      # This is customized lua containerd log format converter, you can refer here:
	      # https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/templates/fluentbit-clusterfilter-containerd.yaml
	      # https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/templates/fluentbit-containerd-config.yaml
	      enable: true
	    systemd:
	      enable: false
	
	fluentd:
	  enable: true
	  name: fluentd
	  port: 24224
	  image:
	    repository: "kubesphere/fluentd"
	    tag: "v1.15.3"
	  replicas: 1
	  forward:
	    port: 24224
	  watchedNamespaces:
	    - kube-system
	    - default
	  resources:
	    limits:
	      cpu: 500m
	      memory: 500Mi
	    requests:
	      cpu: 100m
	      memory: 128Mi
	  # Configure the output plugin parameter in Fluentd.
	  # Fluentd is disabled by default, if you enable it make sure to also set up an output to use.
	  output:
	    opensearch:
	      enable: false
	    es:
	      enable: false
	      host: elasticsearch-logging-data.kubesphere-logging-system.svc
	      port: 9200
	      logstashPrefix: ks-logstash-log
	      buffer:
	        enable: false
	        type: file
	        path: /buffers/es
	    kafka:
	      enable: false
	      brokers: "my-cluster-kafka-bootstrap.default.svc:9091,my-cluster-kafka-bootstrap.default.svc:9092,my-cluster-kafka-bootstrap.default.svc:9093"
	      topicKey: kubernetes_ns
	      buffer:
	        enable: false
	        type: file
	        path: /buffers/kafka
	
	nameOverride: ""
	fullnameOverride: ""
	namespaceOverride: "monitoring"
</details>

I then render the operator using

`helm template fluent-operator https://github.com/fluent/fluent-operator/releases/download/v2.1.0/fluent-operator.tgz -f values.yaml --include-crds > rendered-fluent-operator.yaml`

Then just apply it

### Expected behavior

The operator doesn't crash.

### Your Environment

```markdown
- Fluent Operator version: 2.1.0
- Container Runtime: containerd
- Operating system: linux
- Kernel version: 5.4.0-1103-azure
```

**Comment by adiforluls** [comment]
I think the problem stems from
```
  container:
    repository: "kubesphere/fluent-operator"
    tag: "latest"
```
Instead of latest, change it to v2.1.0

**Comment by Waidmann** [comment]
You're absolutely right, I'm an idiot.
