### ISSUE TITLE
Docs  website 

### ISSUE THREAD

**Issue by jynolen** [fluent/fluent-operator#659]
### Is your feature request related to a problem? Please describe.

Would it be possible to embed the docs in a nice website to make navigation over ressources more confortable ?
Fluentd & fluent-bit have their own why not the operator.

### Describe the solution you'd like

A gitbook site for the operator (or other docgen)

**Comment by benjaminhuo** [comment]
@jynolen we have the idea of having a website for fluent-operator, we just short of hand.
If you're interested in helping maintaining and creating the website, it'll be great.
We can start by creating a hugo repo in fluent org(need @patrick-stephens and @agup006 's help), and deploy it on netlify

**Comment by jynolen** [comment]
I will be glad to help with the small amount of time I got :-D

**Comment by benjaminhuo** [comment]
> I will be glad to help with the small amount of time I got :-D

Great! @patrick-stephens , are you using gitbook to set up fluentbit and fluentd docs websites?
I think we need a new repo called fluent-operator-docs!

**Comment by patrick-stephens** [comment]
I'm afraid I have little knowledge of the overall set up for docs but it is all handled here for Fluent Bit: https://github.com/fluent/fluent-bit-docs

We really need a better way of tracking these requests for new repos, at the moment it is all a little ad-hoc. I'll defer to @agup006 just to confirm he's ok with it but I have no issue with creating it. Please document all set up including users you want access and at what level (e.g. admin vs maintain vs write). Personally I would recommend creating a team and managing access that way, then just add/remove people to the team.
