### ISSUE TITLE
Fluentd as a daemonset

### ISSUE THREAD

**Issue by jjsiv** [fluent/fluent-operator#755]
### Is your feature request related to a problem? Please describe.

Following up on the topic initially started in #632, I'd like to get some input on running Fluentd as a daemonset and possible implementation.

### Describe the solution you'd like

Background: currently it is only possible to run Fluentd as a StatefulSet with Fluent Operator. Some users might find it useful to be able to run Fluentd as a daemonset for collection of logs in cases where some advanced processing is needed which FluentBit either cannot handle or would make it more difficult than necessary.

If there's agreement that this would be worth implementing, how should we approach it?
1. Create a new controller to run Fluentd as a DaemonSet, similarly to how we have FluentBit and Collector controllers - in that case, what would be a good name for it?
2. Utilize the same controller and have a flag in the Fluentd spec to run as a daemonset. I believe this might cause some confusion with some options applying only to running as a statefulset and some only to running as a daemonset?
3. Is there anything else that should be kept in mind with regards to either option? Something that I might have missed?

Looking forward to seeing some opinions on this!

**Comment by adiforluls** [comment]
Hi @jjsiv , wanted to know if you're interested in implementing this enhancement or have already started on the implementation. I'm somewhat interested as well to have this and might do this (or someone from my org does it) as time permits in the coming weeks if you're occupied. Just making sure that the work and effort isn't replicated :)

**Comment by jjsiv** [comment]
Hey, I did originally intend to work on this but have not started with anything and I've been rather busy with other things lately. Feel free to take this.
