### ISSUE TITLE
Request for Releasing Fluent-Operator 2.3.0

### ISSUE THREAD

**Issue by felfa01** [fluent/fluent-operator#763]
### Is your feature request related to a problem? Please describe.

There are some nice features that are currently on master branch but not part of the latest release. Would be great if a new release can be published so that it can referenced and updated in the fluent operator helm chart repo.

### Describe the solution you'd like

Release 2.3.0

**Comment by kaiohenricunha** [comment]
> ### Is your feature request related to a problem? Please describe.
> There are some nice features that are currently on master branch but not part of the latest release. Would be great if a new release can be published so that it can referenced and updated in the fluent operator helm chart repo.
> 
> ### Describe the solution you'd like
> Release 2.3.0
> 
> ### Additional context
> _No response_

Indeed. I need securityContext and volume specs on Fluentd.

**Comment by wenchajun** [comment]
fluent-operatorv2.3 has been released, for details please check  https://github.com/fluent/fluent-operator/releases/tag/v2.3.0
