### ISSUE TITLE
Request to add stripUnderscores in FluentOperator Helm Chart for Fluentbit Systemd input

### ISSUE THREAD

**Issue by karan56625** [fluent/fluent-operator#774]
### Is your feature request related to a problem? Please describe.

As of now, there is no way to use `stripUnderscores` in FluentOperator Helm Chart for Fluentbit Systemd Input. User need to modify the System Fluentbit Input to remove the underscore prefix from Systemd logs. If we allow that change from the Helm Chart Values that would be convenient for the customer.

### Describe the solution you'd like

Add `stripUnderscores` in fluentOperator Helm Chart values under fluentbit.input.systemd.stripUnderscores. By default value should be "off"

**Comment by ksdpmx** [comment]
> As of now, there is no way to use stripUnderscores in FluentOperator Helm Chart for Fluentbit Systemd Input

`stripUnderscores` for fluentbit `systemd` input is supported from the operator.
the default value from fluentbit is `off` although there's no default value and no such field here.
