### ISSUE TITLE
Adding Datadog output fluentd plugin

### ISSUE THREAD

**Issue by joshuabaird** [fluent/fluent-operator#797]
### Is your feature request related to a problem? Please describe.

I know that we can use `customPlugins` on the FluentdSpec, but this is only helpful for plugins that are packaged with the kubesphere/fluentd image.  In my case, I require the output plugin for [Datadog](https://github.com/DataDog/fluent-plugin-datadog).  

How can I install this plugin? I could use a third party image, but I think this will break the auto-reload config functionality that is baked into the kubesphere image.

Also - where is the source for the kubesphere/fluentd images?

### Describe the solution you'd like

A way to install third party fluentd plugins.

**Comment by joshuabaird** [comment]
@benjaminhuo I'm going to work on a PR for this.  Would it be acceptable to just add the `fluent-plugin-datadog` plugin to the kubesphere/fluentd image -- enabling us to use `customPlugins` to configure the plugin?  Or -- should the operator/CRDs also be updated to support the plugin?

**Comment by benjaminhuo** [comment]
> @benjaminhuo I'm going to work on a PR for this. Would it be acceptable to just add the `fluent-plugin-datadog` plugin to the kubesphere/fluentd image -- enabling us to use `customPlugins` to configure the plugin? Or -- should the operator/CRDs also be updated to support the plugin?

@joshuabaird That's great!
Adding datadog to fluentd image and using customPlugins is ok.
Adding CRD fields is a plus, it's not mandatory
