### ISSUE TITLE
Support Networking config

### ISSUE THREAD

**Issue by wanjunlei** [fluent/fluent-operator#811]
### Is your feature request related to a problem? Please describe.

[Networking config](https://docs.fluentbit.io/manual/administration/networking) is a unified networking interface that is exposed to components like plugins. This interface abstract all the complexity of general I/O and is fully configurable. It aims to abstract and simplify the network I/O handling, minimize risks and optimize performance.

### Describe the solution you'd like

Following [this](https://docs.fluentbit.io/manual/administration/networking#concepts).

**Comment by localleon** [comment]
This has been fixed in #1261
