### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by vincent-vinf** [fluent/fluent-operator#848]
### Describe the issue

https://github.com/fluent/fluent-operator/blob/35d8e963f761ce7caffc71b3b242fbc12ab90f41/apis/fluentd/v1alpha1/plugins/output/s3.go#L4-L24

**Comment by benjaminhuo** [comment]
Incorrect configuration?

**Comment by vincent-vinf** [comment]
> Incorrect configuration?

Please see this issue: #849
