### ISSUE TITLE
bug: Enabling multiple output plugins at a time for the same match is not working 

### ISSUE THREAD

**Issue by rajasree1993** [fluent/fluent-operator#874]
### Describe the issue

Enabling multiple output plugin for the same match** is not working as copy is not used in the fluentd config

### To Reproduce

Installed fluent operator using helm by enabling opensearch and kafka output plugin from fluentd 
fluentd:
  output:
    opensearch:
      enable: true
      host: opensearch-cluster-master.observability.svc
      logstashPrefix: app
      port: 9200
      buffer:
        enable: true
        type: file
        path: /buffers/opensearch
        chunkLimitSize: 12MB
        flushInterval: 10s
        flushMode: interval
        flushThreadCount: 5
        overflowAction: throw_exception
        retryMaxInterval: "300s"
        retryType: periodic
        retryWait: 5s
        totalLimitSize: 32MB
    kafka:
      enable: true
      brokers: "cloudflow-strimzi-kafka-bootstrap.cloudflow.svc:9092"
      topicKey: app
      defaultTopic: app
      useEventTime: true

Logs are forwarded only to the first matching filer as copy and store is not used 

kubectl logs fluentd-0

OUTPUT

  <match **>
    @id main
    @type label_router
    <route>
      @label "@8a826769d222393c22be0b52ce8e4a48"
      <match>
        namespaces default,kube-system,observability,udm,udm-http,udm-http-new
      </match>
    </route>
  </match>
  <label @8a826769d222393c22be0b52ce8e4a48>
    <filter **>
      @id ClusterFluentdConfig-cluster-fluentd-config::cluster::clusterfilter::fluentd-filter-0
      @type record_transformer
      enable_ruby true
      <record>
        app ${record["kubernetes"]["namespace_name"]
      </record>
    </filter>
    <match **>
      @id ClusterFluentdConfig-cluster-fluentd-config::cluster::clusteroutput::fluentd-output-kafka-0
      @type kafka2
      brokers cloudflow-strimzi-kafka-bootstrap.cloudflow.svc:9092
      topic_key "app"
      use_event_time true
      <buffer>
        @type "file"
        path "/buffers/kafka"
      </buffer>
      <format>
        @type "json"
      </format>
    </match>
    <match **>
      @id ClusterFluentdConfig-cluster-fluentd-config::cluster::clusteroutput::fluentd-output-opensearch-0
      @type opensearch
      host "opensearch-cluster-master.observability.svc"
      logstash_format true
      logstash_prefix "app"
      port 9200
      <buffer>
        @type "file"
        path "/buffers/opensearch"
      </buffer>
    </match>
  </label>

### Expected behavior

Logs must be forwarded to both the output plugin

You may use something similar like below :

    output.conf: |
      <match **>
        @type copy
        <store>
          @type relabel
          @label @NFEXCEPTIONlogs
        </store>
      </match>

      <label @NFEXCEPTIONlogs>
        <match **>
          @type copy
          #uncomment to forward logs to syslog endpoint
          #<store>
            #@type remote_syslog
            #host
            #port
          #</store>
          <store>
            @type stdout
          </store>
          <store>
            @id elasticnfexception
            @type elasticsearch
            @log_level info
            include_tag_key false
           # Replace with the host/port to your Elasticsearch cluster.
            host "#{ENV['OUTPUT_HOST']}"
            port "#{ENV['OUTPUT_PORT']}"
            scheme "#{ENV['OUTPUT_SCHEME']}"
            ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
            logstash_format true
            logstash_prefix Events-NfException
            type_name _doc
          </store>
        </match>
      </label>

### Your Environment

```markdown
- Fluent Operator version: v1.6.1
- Container Runtime: 
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
- Operating system: Kubernetes 1.27
- Kernel version: 4.18.0-305.el8.x86_64
```

### How did you install fluent operator?

helm way

**Comment by benjaminhuo** [comment]
I suggest trying Fluent Operator v2.4.0 https://github.com/fluent/fluent-operator/releases/tag/v2.4.0 which contains lots of fixes. Same for issue https://github.com/fluent/fluent-operator/issues/872 and https://github.com/fluent/fluent-operator/issues/873

**Comment by rajasree1993** [comment]
hi https://github.com/fluent/fluent-operator/blob/v2.4.0/charts/fluent-operator/templates/fluentd-filter-kafka.yaml i dont see that fix for https://github.com/fluent/fluent-operator/issues/872 in version 2.4.0
same case with [874 ](https://github.com/fluent/fluent-operator/issues/874) and same case with [873](https://github.com/fluent/fluent-operator/issues/873)

**Comment by applike-ss** [comment]
I am struggling across the same issue. Maybe this issue should be renamed to something like `FR: Add copy output plugin support`?
