### ISSUE TITLE
bug: There is no option to configure imagePullSecret for fluentd in values file

### ISSUE THREAD

**Issue by rajasree1993** [fluent/fluent-operator#879]
### Describe the issue

 There is no option to configure imagePullSecret for fluentd in values file. 

### To Reproduce

Configure imagePullSecret  in fluentd values file. It will not be taken into effect 

### Expected behavior

There should be provision to configure imagePullSecret in fluentd section of values.yaml and it has to be applied successfully

### Your Environment

```markdown
- Fluent Operator version: v1.6.1
- Container Runtime: 
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
- Operating system: Kubernetes 1.27
- Kernel version: 4.18.0-305.el8.x86_64
```

### How did you install fluent operator?

helm way

**Comment by Rajan-226** [comment]
@benjaminhuo Can I pick this? Possible to add some more details for starting out?

**Comment by Rajan-226** [comment]
@wenchajun Can you review https://github.com/fluent/fluent-operator/pull/891?
