### ISSUE TITLE
Allow for extra env vars in fluentd helm chart.

### ISSUE THREAD

**Issue by andcri** [fluent/fluent-operator#942]
### Is your feature request related to a problem? Please describe.

Hello, I m trying to add some env vars to the fluentd pod trough the helm chart of the fluent-operator.
I see that that feature exists in the fluentbit template but not in the fluentd one.

### Describe the solution you'd like

I see here https://github.com/fluent/fluent-operator/blob/master/pkg/operator/sts.go#L144-L146 that fluentd supports the addition of extra environment variables by adding the `EnvVars` is it possible to have that added in the template here https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/templates/fluentd-fluentd.yaml in the same way that is added in the fluentbit template?

Thanks :)

**Comment by wenchajun** [comment]
Yes，it is the same, you can refer here https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/fluentd_types.go#L60
