### ISSUE TITLE
bug: ClusterFilter with recordTransformer doesn't handle parameter renewRecord

### ISSUE THREAD

**Issue by nkaijala-elisa** [fluent/fluent-operator#959]
### Describe the issue

renewRecord is set to true in the manifest and the live ClusterFilter resource. It doesn't get applied in the generated fluentd config.

### To Reproduce

Create a ClusterFilter with
```
spec:
  filters:
  - recordTransformer:
      renewRecord: true
      keepKeys: "message"
```

### Expected behavior

A renewed record with one key kept.

### Your Environment

```markdown
- Fluent Operator version: v1.15.3
- Container Runtime: CRI-O, on OpenShift 4.11
- Operating system: RHEL 8.6
- Kernel version: 4.18.0
```

### How did you install fluent operator?

- Helm install
- Installed Fluentd CRDs
- Installed Fluentd in fluentd-only -mode
- Set up Security Context Constraints (OpenShift requirement)

### Additional context

fluentd pod logs:
```
2023-10-16 08:36:09 +0000 [info]: adding filter in @db681e4cb763ca5b7cdbf9ab76f67bbe pattern="**" type="record_transformer"
2023-10-16 08:36:09 +0000 [error]: #0 config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="`renew_record` must be true to use `keep_keys`"
2023-10-16 08:36:09 +0000 [error]: Worker 0 exited unexpectedly with status 2
2023-10-16 08:36:09 +0000 [info]: Received graceful stop
level=error msg="Fluentd exited" error="exit status 2"
level=info msg=backoff delay=1s
level=info msg="backoff timer done" actual=1.000610697s expected=1s
```
ClusterFilter yaml:
```
$ oc get clusterfilters.fluentd.fluent.io fluentd-filter -o yaml

...
spec:
  filters:
  - recordTransformer:
      keepKeys: message
      renewRecord: true
```

**Comment by cw-Guo** [comment]
due to a bug in fluentd recordTransformer plugin, missed insert a parameter, see [code](https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/plugins/filter/types.go#L151)
